export * from './admissionStaff.entity';
export * from './AIDiagnosisResult.entity';
export * from './AIResultDisease.entity'
export * from './appointment.entity';
export * from './chatbot.entity';
export * from './chatbotQuery.entity';
export * from './chatHistory.entity';
export * from './consultation.entity';
export * from './dataInstance.entity';
export * from './diagnoseModel.entity';
export * from './diagnosisResult.entity';
export * from './disease.entity';
export * from './doctor.entity';
export * from './image.entity';
export * from './patient.entity';
export * from './schedule.entity';
export * from './shift.entity';
// export * from './room.entity';
export * from './resultDisease.entity'
export * from './user.entity';
export * from './workingTime.entity';