export enum INJECTION_TOKEN {
  USER_SERVICE = 'USER_SERVICE',
  AUTH_SERVICE = 'AUTH_SERVICE',
  OTP_SERVICE = 'OTP_SERVICE',
  CACHE_SERVICE = 'CACHE_SERVICE',
  SHIFT_SERVICE = 'SHIFT_SERVICE',
  DOCTOR_SERVICE = 'DOCTOR_SERVICE',
  DIFY_CACHE_SERVICE = 'DIFY_CACHE_SERVICE',
  EMBEDDED_CHAT_SERVICE = 'EMBEDDED_CHAT_SERVICE',
  PATIENT_SERVICE = 'PATIENT_SERVICE',
  APPOINTMENT_SERVICE = 'APPOINTMENT_SERVICE',
  CONSULTATION_SERVICE = 'CONSULTATION_SERVICE',
  STAFF_SERVICE = 'STAFF_SERVICE',
  ADMIN_SERVICE = 'ADMIN_SERVICE',
}

export enum REPOSITORY_INJECTION_TOKEN {
  USER_REPOSITORY = 'USER_REPOSITORY',
  ADMISSION_STAFF_REPOSITORY = 'ADMISSION_STAFF_REPOSITORY',
  AI_DIAGNOSIS_RESULT_REPOSITORY = 'AI_DIAGNOSIS_RESULT_REPOSITORY',
  AI_RESULT_DISEASE_REPOSITORY = 'AI_RESULT_DISEASE_REPOSITORY',
  APPOINTMENT_REPOSITORY = 'APPOINTMENT_REPOSITORY',
  CHATBOT_REPOSITORY = 'CHATBOT_REPOSITORY',
  CHATBOT_QUERY_REPOSITORY = 'CHATBOT_QUERY_REPOSITORY',
  CHAT_HISTORY_REPOSITORY = 'CHAT_HISTORY_REPOSITORY',
  CONSULTATION_REPOSITORY = 'CONSULTATION_REPOSITORY',
  DATA_INSTANCE_REPOSITORY = 'DATA_INSTANCE_REPOSITORY',
  DIAGNOSE_MODEL_REPOSITORY = 'DIAGNOSE_MODEL_REPOSITORY',
  DIAGNOSIS_RESULT_REPOSITORY = 'DIAGNOSIS_RESULT_REPOSITORY',
  DISEASE_REPOSITORY = 'DISEASE_REPOSITORY',
  DOCTOR_REPOSITORY = 'DOCTOR_REPOSITORY',
  END_USER_REPOSITORY = 'END_USER_REPOSITORY',
  IMAGE_REPOSITORY = 'IMAGE_REPOSITORY',
  PATIENT_REPOSITORY = 'PATIENT_REPOSITORY',
  RESULT_DISEASE_REPOSITORY = 'RESULT_DISEASE_REPOSITORY',
  ROOM_REPOSITORY = 'ROOM_REPOSITORY',
  SCHEDULE_REPOSITORY = 'SCHEDULE_REPOSITORY',
  SHIFT_REPOSITORY = 'SHIFT_REPOSITORY',
  WORKING_TIME_REPOSITORY = 'WORKING_TIME_REPOSITORY',
}

export enum INFRASTRUCTURE_INJECTION_TOKEN {
  CLOUD_STORAGE_SERVICE = 'CLOUD_STORAGE_SERVICE',
}
