export enum INJECTION_TOKEN {
  USER_SERVICE = 'USER_SERVICE',
  AUTH_SERVICE = 'AUTH_SERVICE',
  OTP_SERVICE = 'OTP_SERVICE',
  CACHE_SERVICE = 'CACHE_SERVICE',
}

export enum REPOSITORY_INJECTION_TOKEN {
  USER_REPOSITORY = 'USER_REPOSITORY',
  END_USER_REPOSITORY = 'END_USER_REPOSITORY'
}

export enum INFRASTRUCTURE_INJECTION_TOKEN {
  CLOUD_STORAGE_SERVICE = 'CLOUD_STORAGE_SERVICE',
}
