import { Inject, Logger } from '@nestjs/common';
import { CommandHandler, ICommand, ICommandHandler } from '@nestjs/cqrs';

import { REPOSITORY_INJECTION_TOKEN } from '@api/enums';
import {
  IAIDiagnosisResultRepository,
  IAIResultDiseaseRepository,
  IDiseaseRepository,
} from '@api/repository';
import { Transactional } from 'typeorm-transactional';
import { v4 as uuidv4 } from 'uuid';

import { SeverityLevel } from '@app/core/domain/enums';
import { AiInternalServerError } from '@app/core/exception';

import { HandleAiDiagnosisCallbackRequestDto } from '../dtos/request/handle-ai-diagnosis-callback.request.dto';

export class HandleAiDiagnosisCallbackCommand implements ICommand {
  constructor(public readonly payload: HandleAiDiagnosisCallbackRequestDto) {}
}

@CommandHandler(HandleAiDiagnosisCallbackCommand)
export class HandleAiDiagnosisCallbackCommandHandler
  implements ICommandHandler<HandleAiDiagnosisCallbackCommand, void>
{
  private readonly logger = new Logger(HandleAiDiagnosisCallbackCommandHandler.name);

  constructor(
    @Inject(REPOSITORY_INJECTION_TOKEN.AI_DIAGNOSIS_RESULT_REPOSITORY)
    private readonly aiDiagnosisResultRepository: IAIDiagnosisResultRepository,
    @Inject(REPOSITORY_INJECTION_TOKEN.DISEASE_REPOSITORY)
    private readonly diseaseRepository: IDiseaseRepository,
    @Inject(REPOSITORY_INJECTION_TOKEN.AI_RESULT_DISEASE_REPOSITORY)
    private readonly aiResultDiseaseRepository: IAIResultDiseaseRepository,
  ) {}

  @Transactional()
  async execute(command: HandleAiDiagnosisCallbackCommand): Promise<void> {
    try {
      const { payload } = command;

      // 1. Find or create the Disease
      let diseaseRecord = await this.diseaseRepository.findOne({
        where: { name: payload.disease },
      });

      diseaseRecord ??= await this.diseaseRepository.create({
          name: payload.disease,
          description: 'Auto-generated by AI model',
        });

      // 2. Find or create AIDiagnosisResult
      let diagnosisResult = await this.aiDiagnosisResultRepository.findOne({
        where: { consultationId: payload.consultationId },
      });

      if (diagnosisResult) {
        // Update existing
        diagnosisResult = await this.aiDiagnosisResultRepository.update(
          diagnosisResult.id,
          {
            suggestedDiagnosis: [{ diseaseName: payload.disease, accuracy: payload.probability }],
            aiAdvice: payload.aiAdvice,
            diagnoseModelId: payload.diagnoseModelId,
          }
        );
      } else {
        diagnosisResult = await this.aiDiagnosisResultRepository.create({
          consultationId: payload.consultationId,
          diagnoseModelId: payload.diagnoseModelId,
          suggestedDiagnosis: [{ diseaseName: payload.disease, accuracy: payload.probability }],
          aiAdvice: payload.aiAdvice,
          severityLevel: SeverityLevel.MODERATE,
        });
      }

      // 3. Create or update AIResultDisease
      await this.aiResultDiseaseRepository.create({
        resultId: diagnosisResult.id,
        diseaseId: diseaseRecord.id,
        accuracy: payload.probability,
      });

      this.logger.log(
        `Successfully saved AI Diagnosis Result for consultation ${payload.consultationId}`,
      );
    } catch (error) {
      this.logger.error(
        `Failed to process AI diagnosis callback: ${error?.message}`,
        error?.stack,
      );
      throw new AiInternalServerError(
        'Database error during AI diagnosis callback',
      );
    }
  }
}
