import { Inject, Logger } from '@nestjs/common';
import { CommandHandler, ICommand, ICommandHandler } from '@nestjs/cqrs';

import { REPOSITORY_INJECTION_TOKEN } from '@api/enums';
import {
  IAIDiagnosisResultRepository,
  IAIResultDiseaseRepository,
  IDiseaseRepository,
} from '@api/repository';
import { Transactional } from 'typeorm-transactional';
import { v4 as uuidv4 } from 'uuid';

import { SeverityLevel } from '@app/core/domain/enums';
import { AiInternalServerError } from '@app/core/exception';

import { HandleAiDiagnosisCallbackRequestDto } from '../dtos/request/handle-ai-diagnosis-callback.request.dto';

export class HandleAiDiagnosisCallbackCommand implements ICommand {
  constructor(public readonly payload: HandleAiDiagnosisCallbackRequestDto) {}
}

@CommandHandler(HandleAiDiagnosisCallbackCommand)
export class HandleAiDiagnosisCallbackCommandHandler
  implements ICommandHandler<HandleAiDiagnosisCallbackCommand, void>
{
  private readonly logger = new Logger(HandleAiDiagnosisCallbackCommandHandler.name);

  constructor(
    @Inject(REPOSITORY_INJECTION_TOKEN.AI_DIAGNOSIS_RESULT_REPOSITORY)
    private readonly aiDiagnosisResultRepository: IAIDiagnosisResultRepository,
    @Inject(REPOSITORY_INJECTION_TOKEN.DISEASE_REPOSITORY)
    private readonly diseaseRepository: IDiseaseRepository,
    @Inject(REPOSITORY_INJECTION_TOKEN.AI_RESULT_DISEASE_REPOSITORY)
    private readonly aiResultDiseaseRepository: IAIResultDiseaseRepository,
  ) {}

  @Transactional()
  async execute(command: HandleAiDiagnosisCallbackCommand): Promise<void> {
    try {
      const { payload } = command;

      // Build lesions list from payload
      const lesions = payload.lesions?.length
        ? payload.lesions
        : [{
            lesionIndex: 0,
            topDisease: payload.disease,
            topProbability: payload.probability,
            severity: payload.severityLevel,
            croppedImage: undefined,
            allPredictions: payload.allPredictions?.length
              ? payload.allPredictions
              : [{ disease: payload.disease, probability: payload.probability, severity: payload.severityLevel }],
          }];

      // suggestedDiagnosis = top disease per lesion (for quick display)
      const suggestedDiagnosis = lesions.map(l => ({
        diseaseName: l.topDisease,
        accuracy: l.topProbability,
      }));

      // proof = [imageWithAllBboxes, ...croppedImages per lesion]
      const proofImages = [
        payload.imageWithAllBboxes,
        ...lesions.map(l => l.croppedImage).filter(Boolean),
      ].filter(Boolean);

      // 1. Save or update AIDiagnosisResult
      let diagnosisResult = await this.aiDiagnosisResultRepository.findOne({
        where: { consultationId: payload.consultationId },
      });

      if (diagnosisResult) {
        diagnosisResult = await this.aiDiagnosisResultRepository.update(
          diagnosisResult.id,
          {
            suggestedDiagnosis,
            aiAdvice: payload.aiAdvice,
            diagnoseModelId: payload.diagnoseModelId,
            proof: JSON.stringify(proofImages),
          }
        );
      } else {
        diagnosisResult = await this.aiDiagnosisResultRepository.create({
          consultationId: payload.consultationId,
          diagnoseModelId: payload.diagnoseModelId,
          suggestedDiagnosis,
          aiAdvice: payload.aiAdvice,
          severityLevel: payload.severityLevel ?? SeverityLevel.MINOR,
          proof: JSON.stringify(proofImages),
        });
      }

      // 2. Save AIResultDisease per lesion per prediction
      await Promise.all(
        lesions.flatMap(lesion =>
          lesion.allPredictions.map(async pred => {
            let diseaseRecord = await this.diseaseRepository.findOne({
              where: { name: pred.disease },
            });

            diseaseRecord ??= await this.diseaseRepository.create({
              name: pred.disease,
              description: 'Auto-generated by AI model',
            });

            await this.aiResultDiseaseRepository.create({
              resultId: diagnosisResult.id,
              diseaseId: diseaseRecord.id,
              lesionIndex: lesion.lesionIndex,
              accuracy: pred.probability,
            });
          })
        )
      );

      this.logger.log(
        `Successfully saved AI Diagnosis Result for consultation ${payload.consultationId}`,
      );
    } catch (error) {
      this.logger.error(
        `Failed to process AI diagnosis callback: ${error?.message}`,
        error?.stack,
      );
      throw new AiInternalServerError(
        'Database error during AI diagnosis callback',
      );
    }
  }
}
