export enum ImageType {
    AVATAR = 'AVATAR',
    PATIENT_SYMPTOMS = 'PATIENT_SYMPTOMS',
    DOCTOR_SYMPTOMS = 'DOCTOR_SYMPTOMS',
    OTHER = 'OTHER'
}

export enum ImageReference {  
    APPOINTMENT = 'APPOINTMENT',
    CONSULTATION = 'CONSULTATION',
    AVATAR = 'AVATAR'
}